### ISSUE TITLE
Quick Review

### ISSUE THREAD

**Issue by mriedmann** [amq/Betriebssysteme-Beispiel-1#1]
Here a quick list of my suggestions (really only my personal opinions):
- your params struct name "params_t" is quite missleading (I would use "params" for the struct and leave "params_t" for the type)
- print,ls,nouser,... fields in params_t could be replaced by an enum (which could increase the readability).
- same goes for the status variable at do_parse_params (currently this function is a bit hard to read)
- Just for the records: Returning the target of a sym-link is a nice thing, but normal find don't behave as cindly as your implementation.
- As I see do_file returns only 2 values (FAILURE, SUCCESS). You can consider using stdbool.h and use true and false for this case.
- At do_file an enum/bitflag-field could lead to much cleaner code (switch?)
- Do you know about error()? It's pretty handy when it comes to outputting error-messages (http://www.gnu.org/software/libc/manual/html_node/Error-Messages.html)
- I think you could replace most of your malloc-calls with VLA. IMHO it's a much safer way to deal with dynamic memory.
- As I know the user-argument should work with user-id and user-name and I haven't found any implementation.

**Comment by amq** [comment]
Thanks!

There is already `params` for the variable and `params_t` for the struct, but maybe I don't understand you correctly.

```
int do_location(params_t *params);
```

`-user` accepts both name and id, it just gets always recorded as `userid` by `do_parse_params`:

```
    if (strcmp(argv[i], "-user") == 0) {
      if (argv[++i]) {
        params->user = argv[i];
        /* check if the user exists */
        if ((pwd = getpwnam(params->user))) {
          params->userid = pwd->pw_uid;
          expression = 1;
          continue;
        }
        /* otherwise, if the input is a number, use that */
        if (sscanf(params->user, "%u", &params->userid)) {
          expression = 1;
          continue;
        }
        status = 4;
        break; /* the user is not found and not a number */
      } else {
        status = 2;
        break; /* the second part is missing */
      }
    }
```

**Comment by mriedmann** [comment]
ok now i see ... must have overlooked it somehow, sorry.

I meant this part:

```
typedef struct params_t {
...
} params_t;
```

The actual struct is defined as "params_t" as well as the type defined by typedef. This could be irritating and is not considered as "good style". Alternatively you could simply omit the struct name and use a "anonymous" struct

```
typedef struct {
...
} params_t;
```

**Comment by osiyuk** [comment]
Ok. I have a quick suggestion to logic part of the code.
Instead of using `else` part, you can simplify things, omit the `else` and go less indentation.
```
if (strcmp(argv[i], "-user") == 0) {
  if (argv[++i]) {
    params->user = argv[i];
    /* check if the user exists */
    if ((pwd = getpwnam(params->user))) {
      params->userid = pwd->pw_uid;
      expression = 1;
      continue;
    }
    /* otherwise, if the input is a number, use that */
    if (sscanf(params->user, "%u", &params->userid)) {
      expression = 1;
      continue;
    }
    status = 4;
    break; /* the user is not found and not a number */
  } else {
    status = 2;
    break; /* the second part is missing */
  }
}
```
Break conditional logic as early as possible:
```
if (strcmp(argv[i], "-user") == 0) {
  if (!argv[++i]) {
    status = 2;
    break; /* the second part is missing */
  }
  params->user = argv[i];
  /* check if the user exists */
  if ((pwd = getpwnam(params->user))) {
    params->userid = pwd->pw_uid;
    expression = 1;
    continue;
  }
  /* otherwise, if the input is a number, use that */
  if (sscanf(params->user, "%u", &params->userid)) {
    expression = 1;
    continue;
  }
  status = 4;
  break; /* the user is not found and not a number */
}
```
